# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.98.0"

default_platform :ios

platform :ios do

# before_all do |lane, options|
#    @run_once_before_all ||= begin

#    import_from_git(url: 'git@github.com:CruGlobal/mobile-deployment-config.git', path: 'ios/Fastfile')

# end

lane :production do

    cert(
  #      username: "ryan.t.carlson@cru.org"
    )


    sigh(
  #      username: "ryan.t.carlson@cru.org",
        app_identifier: "org.cru.godtools",
    )

    gym(
        scheme: "godtools",
        configuration: "Release",
    )

    deliver(
   #     username: "ryan.t.carlson@cru.org",
    )
end

end
